version: '3'

services:
  web:
    image: $REGISTRY/$IMAGE_NAME:latest
    container_name: web
    depends_on:
      - db
    environment:
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - DATABASE_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - SMTP_HOST=${SMTP_HOST}
      - STMP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    volumes:
      # persist public and media files to the host machine
      - ./public:/app/public
  db:
    image: postgres:15
    container_name: postgres 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  caddy: 
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    restart: always
    

volumes:
  postgres_data:
  caddy_data:
  caddy_config:


