name: Deploy to Production

on:
  push:
    branches:
      - main
env:
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/learngrow:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/learngrow:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker-compose down
            docker-compose pull web
            docker-compose -f docker-compose.prod.yml up -d 
